# Generated by Django 5.1.4 on 2025-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name']},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-name'], name='pageApp_per_name_5c5f87_idx'),
        ),
    ]
